name: update, build and merge with PR

on:
  workflow_call:
    inputs:
      git_mail:
        description: 'email to use'
        required: true

jobs:

  update-flake-reuse:
    uses: MadMcCrow/flake-github-workflow/.github/workflows/update_flake.yml@main

  pull-request-reuse:
    needs: [update-flake-reuse]
    uses: MadMcCrow/flake-github-workflow/.github/workflows/pull_request.yml@main