name: 'Clean workflows runs'


on:
  workflow_call:
    inputs:
      repository:
        type: string
        default: ${{ github.repository }}
      # number of successful run to keep
      success_count:
        # type is one of [string, choice, boolean, environment]
        type: string
        default: 1
        required: false
      # number of failed run to keep
      failed_count:
        type: string
        default: 3
        required: false
       
jobs:

  del_succesful_runs:
    runs-on: ubuntu-latest
    steps:
      - name: Delete workflow runs
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ github.token }}
          repository: ${{inputs.repository}}
          keep_minimum_runs: ${{inputs.success_count}}
          delete_run_by_conclusion_pattern: success
          retain_days: 0 # delete all but the latest, only keeping count
  
  del_failed_runs:
    runs-on: ubuntu-latest
    steps:
      - name: Delete workflow runs
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ github.token }}
          repository: ${{inputs.repository}}
          keep_minimum_runs: ${{inputs.failed_count}}
          delete_run_by_conclusion_pattern: failure
          retain_days: 0 # delete all but the latest, only keeping count