name: 'Clean workflows runs'

on:
  workflow_call:
    inputs:
      success_count:
        default: 1
        required: false

      failed_count:
        default: 3
        required: false
       
jobs:

  del_succesful_runs:
    runs-on: ubuntu-latest
    steps:
      - name: Delete workflow runs
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
          keep_minimum_runs: ${{inputs.success_count}}
          delete_run_by_conclusion_pattern: success
  
  del_failed_runs:
    runs-on: ubuntu-latest
    steps:
      - name: Delete workflow runs
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
          keep_minimum_runs: ${{inputs.failed_count}}
          delete_run_by_conclusion_pattern: failed