name: update, build and merge with PR

on:
  workflow_call:
    inputs:
      git_mail:
        description: 'email to use'
        required: true

jobs:

  update-flake-reuse:
    uses: ./.github/workflows/update-flake.yml

  pull-request-reuse:
    needs: [update-flake-reuse]
    uses: ./.github/workflows/pull-request.yml