name: 'Pull Request'

on:
  workflow_call:
    inputs:
      git_email:
        type: string
        required: false
        default: 'noe.perard+git@gmail.com'
      assignee:
        type: string
        required: false
        default: 'MadMcCrow'
      commit:  
        type: string
        required: false
        default: ':robot: github action'
      pr_title:  
        type: string
        required: false
        default: ':robot: github action'
      pr_message:  
        type: string
        required: false
        default: ':robot: github action on $(date -I)'

jobs:
 push_update:
    runs-on: ubuntu-20.04
    permissions: write-all
    steps:
    - uses: actions/checkout@v3
    - name: Restore flake.lock
      uses: actions/download-artifact@v3
      with:
        name: flake_lock
    - name: Set up git
      run: |
        git config user.email ${{inputs.git_email}}
        git config user.name "Git Bot"
    - name: Create and merge PR
      run: |
          git switch -c updates-${{ github.run_id }}
          git commit -am "${{ inputs.commit }}"
          git push -u origin updates-${{ github.run_id }}
          PR=$(gh pr create \
            --assignee ${{ inputs.assignee }} \
            --base main \
            --body "${{inputs.pr_message}}" \
            --fill \
            --label bot \
            --title "Auto update $(date -I)")
          gh pr merge $PR --merge --delete-branch
      env:
        GITHUB_TOKEN: ${{ github.token }}
