name: 'Pull Request'

description: 'Create a pull request and merge it'

on:
  workflow_call:
    inputs:
      assignee:
        description: 'who to assign PR to'
        required: false
        default: 'MadMcCrow'
      commit:  
        description: 'commit message'
        required: false
        default: ':robot: github action'
      pr_title:  
        description: 'Pull request title'
        required: false
        default: ':robot: github action'
      pr_message:  
        description: 'Pull request body message'
        required: false
        default: ':robot: github action on $(date -I)'

jobs:
 push_update:
    runs-on: ubuntu-20.04
    permissions: write-all
    needs: [update_flake, build_flake, check_flake]
    steps:
    - uses: actions/checkout@v3
    - name: Restore flake.lock
      uses: actions/download-artifact@v3
      with:
        name: flake_lock
    - name: Set up git
      run: |
        git config user.email ${{inputs.git_email}}
        git config user.name "Git Bot"
    - name: Create and merge PR
      run: |
          git switch -c updates-${{ github.run_id }}
          git commit -am "${{ inputs.commit }}"
          git push -u origin updates-${{ github.run_id }}
          PR=$(gh pr create \
            --assignee ${{ inputs.assignee }} \
            --base main \
            --body "${{inputs.pr_message}}" \
            --fill \
            --label bot \
            --title "Auto update $(date -I)")
          gh pr merge $PR --merge --delete-branch
      env:
        GITHUB_TOKEN: ${{ github.token }}
